//SERVICES
export const INJECTION_SERVICE_AUTH = '@INJECTION_SERVICE_AUTH';

// USE CASES
export const INJECTION_USECASE_AUTH = '@INJECTION_USECASE_AUTH';
export const INJECTION_USECASE_FORGOT = '@INJECTION_USECASE_FORGOT';
export const INJECTION_USECASE_RESET = '@INJECTION_USECASE_RESET';
