// REPOSITORIES
export const INJECTION_REPOSITORY_USER = '@INJECTION_REPOSITORY_USER';
export const INJECTION_REPOSITORY_VALIDATION_CODE =
  '@INJECTION_REPOSITORY_VALIDATION_CODE';

//SERVICES
export const INJECTION_SERVICE_CREATE_USER = '@INJECTION_SERVICE_CREATE_USER';
export const INJECTION_SERVICE_UPDATE_USER = '@INJECTION_SERVICE_UPDATE_USER';
export const INJECTION_SERVICE_FINDBY_USER = '@INJECTION_SERVICE_FINDBY_USER';
export const INJECTION_SERVICE_FINDBY_VALIDATION_CODE =
  '@INJECTION_SERVICE_FINDBY_VALIDATION_CODE';
export const INJECTION_SERVICE_CREATE_VALIDATION_CODE =
  '@INJECTION_SERVICE_CREATE_VALIDATION_CODE';
export const INJECTION_SERVICE_DELETE_VALIDATION_CODE =
  '@INJECTION_SERVICE_DELETE_VALIDATION_CODE';
export const INJECTION_SERVICE_AUTH = '@INJECTION_SERVICE_AUTH';

// USE CASES
export const INJECTION_USECASE_CREATE_USER = '@INJECTION_USECASE_CREATE_USER';
export const INJECTION_USECASE_UPDATE_USER = '@INJECTION_USECASE_UPDATE_USER';
export const INJECTION_USECASE_FINDBY_USER = '@INJECTION_USECASE_CREATE_USER';
export const INJECTION_USECASE_AUTH = '@INJECTION_USECASE_AUTH';
export const INJECTION_USECASE_FINDBY_VALIDATION_CODE =
  '@INJECTION_USECASE_FINDBY_VALIDATION_CODE';
export const INJECTION_USECASE_CREATE_VALIDATION_CODE =
  '@INJECTION_USECASE_CREATE_VALIDATION_CODE';
export const INJECTION_USECASE_DELETE_VALIDATION_CODE =
  '@INJECTION_USECASE_DELETE_VALIDATION_CODE';
