// REPOSITORIES
export const INJECTION_REPOSITORY_VALIDATION_CODE =
  '@INJECTION_REPOSITORY_VALIDATION_CODE';

//SERVICES

export const INJECTION_SERVICE_FINDBY_VALIDATION_CODE =
  '@INJECTION_SERVICE_FINDBY_VALIDATION_CODE';
export const INJECTION_SERVICE_CREATE_VALIDATION_CODE =
  '@INJECTION_SERVICE_CREATE_VALIDATION_CODE';
export const INJECTION_SERVICE_DELETE_VALIDATION_CODE =
  '@INJECTION_SERVICE_DELETE_VALIDATION_CODE';
